from pathlib import Path
p=Path("index.html")
s=p.read_text(encoding="utf-8")

def must(old,new,label):
    global s
    n=s.count(old)
    if n!=1:
        raise SystemExit(f"{label}: expected 1 occurrence, found {n}")
    s=s.replace(old,new,1)

must("calculationVersion:'v2-offline-savings-draft-0.3'","calculationVersion:'v3-bill-switch-optimistic-1.0'","calculation version")
must('<input name="pv_existing"><input name="roof_available"><input name="bill_path">','<input name="pv_existing"><input name="bill_path">',"remove roof form field")
must('<input name="lead_type"><input name="fv_intent"><input name="contact_preference">','<input name="lead_type"><input name="bill_switch_intent"><input name="contact_preference">',"rename intent form field")
must("const state={screen:0,profileType:'',billPath:'',billFileUploaded:false,monthlySpend:0,annualKwh:0,annualSpend:0,dataQuality:'ESTIMATED_FROM_SPEND',ownerStatus:'',pvExisting:'',roofAvailable:'',fvIntent:'',contactPreference:'',result:null,intakeSaved:false,lastIntakeFingerprint:''};","const state={screen:0,profileType:'',billPath:'',billFileUploaded:false,monthlySpend:0,annualKwh:0,annualSpend:0,dataQuality:'ESTIMATED_FROM_SPEND',ownerStatus:'',pvExisting:'',billSwitchIntent:'',contactPreference:'',result:null,intakeSaved:false,lastIntakeFingerprint:''};","state intent and roof")
must('<div id="roofBlock" class="hidden"><div class="sectionLabel">Hai un tetto o una copertura disponibile?</div><div class="choices three" id="roofChoices"><button type="button" class="choice" data-value="Sì" aria-pressed="false">Sì</button><button type="button" class="choice" data-value="Non so" aria-pressed="false">Non so</button><button type="button" class="choice" data-value="No" aria-pressed="false">No</button></div></div>','',"remove roof question")
must('<h2 id="intentQuestion">Se questi numeri fossero confermati, valuteresti il fotovoltaico?</h2>\n        <p class="sub" id="intentSub">La risposta serve solo a capire quale approfondimento può esserti utile.</p>\n        <div class="choices three" id="intentChoices"><button type="button" class="choice" data-value="YES" aria-pressed="false">Sì</button><button type="button" class="choice" data-value="MAYBE" aria-pressed="false">Potrei valutarlo</button><button type="button" class="choice" data-value="NO" aria-pressed="false">No</button></div>','<h2 id="intentQuestion">Se il risparmio fosse confermato, valuteresti il cambio bolletta?</h2>\n        <p class="sub" id="intentSub">La risposta riguarda solo il cambio della fornitura luce.</p>\n        <div class="choices" id="intentChoices"><button type="button" class="choice" data-value="YES" aria-pressed="false">Sì</button><button type="button" class="choice" data-value="NO" aria-pressed="false">No</button></div>',"bill switch intent UI")
must("setupChoice('#ownerChoices',v=>{state.ownerStatus=v;status('#profileHelp','')});\nsetupChoice('#pvChoices',v=>{state.pvExisting=v;$('#roofBlock').classList.toggle('hidden',v!=='No');if(v==='Sì'){state.roofAvailable='';$$('#roofChoices .choice').forEach(b=>{b.classList.remove('active');b.setAttribute('aria-pressed','false')})}status('#profileHelp','')});\nsetupChoice('#roofChoices',v=>{state.roofAvailable=v;status('#profileHelp','')});","setupChoice('#ownerChoices',v=>{state.ownerStatus=v;status('#profileHelp','')});\nsetupChoice('#pvChoices',v=>{state.pvExisting=v;status('#profileHelp','')});","remove roof setup")
must("$('#profileNext').addEventListener('click',()=>{if(!state.profileType){status('#profileHelp','Seleziona il tipo di utenza.');return}if(!state.ownerStatus){status('#profileHelp','Indica se l’immobile è di tua proprietà.');return}if(!state.pvExisting){status('#profileHelp','Indica se hai già il fotovoltaico.');return}if(state.pvExisting==='No'&&!state.roofAvailable){status('#profileHelp','Indica se hai un tetto o una copertura disponibile.');return}state.result=calculate();renderResult();track('energy_profile_completed',{owner_status:state.ownerStatus,pv_existing:state.pvExisting,roof_available:state.roofAvailable});track('savings_calculated',{lead_type:state.result.leadType,total_low:Math.round(state.result.totalLow),total_high:Math.round(state.result.totalHigh)});setScreen(4);track('savings_estimate_viewed',{lead_type:state.result.leadType})});","$('#profileNext').addEventListener('click',()=>{if(!state.profileType){status('#profileHelp','Seleziona il tipo di utenza.');return}if(!state.ownerStatus){status('#profileHelp','Indica se l’immobile è di tua proprietà.');return}if(!state.pvExisting){status('#profileHelp','Indica se hai già il fotovoltaico.');return}state.result=calculate();renderResult();track('energy_profile_completed',{owner_status:state.ownerStatus,pv_existing:state.pvExisting});track('savings_calculated',{lead_type:state.result.leadType,total_low:Math.round(state.result.totalLow),total_high:Math.round(state.result.totalHigh)});setScreen(4);track('savings_estimate_viewed',{lead_type:state.result.leadType})});","remove roof validation")
must("const pvPossible=state.pvExisting==='No'&&state.ownerStatus==='Sì'&&state.roofAvailable!=='No'&&state.profileType!=='Appartamento';","const pvPossible=state.pvExisting==='No'&&state.ownerStatus==='Sì'&&state.profileType!=='Appartamento';","pv eligibility without roof question")
must("const purchaseLow=min('purchase'),purchaseHigh=max('purchase'),pvLow=min('pv'),pvHigh=max('pv'),totalLow=min('total'),totalHigh=max('total');","const rawPurchaseLow=min('purchase'),rawPurchaseHigh=max('purchase'),pvLow=min('pv'),pvHigh=max('pv');\n  const qualityBase=state.dataQuality==='BILL_PARSED'?.88:state.dataQuality==='USER_DECLARED'?.78:.62;\n  const dataScore=Math.min(1,qualityBase+(state.annualKwh>0?.05:0)+((state.annualSpend>0||state.monthlySpend>0)?.05:0)+(state.billFileUploaded?.04:0));\n  const billFloor=105;\n  const spendDrivenLow=annualSpend*(.08+.05*dataScore);\n  const spendDrivenHigh=annualSpend*(.14+.09*dataScore);\n  const modeledLow=Math.max(rawPurchaseLow,spendDrivenLow),modeledHigh=Math.max(rawPurchaseHigh,spendDrivenHigh);\n  const lowSurplus=Math.max(0,modeledLow-billFloor),highSurplus=Math.max(20,modeledHigh-billFloor);\n  const purchaseLow=billFloor+lowSurplus*(.65+.25*dataScore);\n  const purchaseHigh=Math.max(purchaseLow+20,billFloor+highSurplus*(.90+.20*dataScore));\n  const totalLow=purchaseLow+pvLow,totalHigh=purchaseHigh+pvHigh;","optimistic bill savings model")
must("function prepareIntentQuestion(){if(state.pvExisting==='Sì'){$('#intentQuestion').textContent='Se ci fosse margine, valuteresti un’ottimizzazione del tuo sistema energetico?';$('#intentSub').textContent='Possiamo verificare fornitura, autoconsumo, accumulo e gestione dell’impianto esistente.'}else if(state.result&&!state.result.pvPossible){$('#intentQuestion').textContent='Se fosse tecnicamente praticabile, valuteresti il fotovoltaico?';$('#intentSub').textContent='La fattibilità reale va verificata sull’immobile e sulla disponibilità della copertura.'}else{$('#intentQuestion').textContent='Se questi numeri fossero confermati, valuteresti il fotovoltaico?';$('#intentSub').textContent='La risposta serve solo a capire quale approfondimento può esserti utile.'}}","function prepareIntentQuestion(){$('#intentQuestion').textContent='Se il risparmio fosse confermato, valuteresti il cambio bolletta?';$('#intentSub').textContent='La risposta riguarda solo il cambio della fornitura luce.'}","fixed bill switch intent question")
must("setupChoice('#intentChoices',v=>{state.fvIntent=v;status('#intentHelp','');track('fv_intent_selected',{value:v})});\n$('#intentNext').addEventListener('click',()=>{if(!state.fvIntent){status('#intentHelp','Seleziona una risposta.');return}setScreen(6)});","setupChoice('#intentChoices',v=>{state.billSwitchIntent=v;status('#intentHelp','');track('bill_switch_intent_selected',{value:v})});\n$('#intentNext').addEventListener('click',()=>{if(!state.billSwitchIntent){status('#intentHelp','Seleziona una risposta.');return}setScreen(6)});","intent behavior")
must("pv_existing:state.pvExisting,roof_available:state.roofAvailable,bill_path:state.billPath","pv_existing:state.pvExisting,bill_path:state.billPath","remove roof outcome")
must("lead_type:r.leadType||'NURTURE',fv_intent:state.fvIntent,contact_preference:preference","lead_type:r.leadType||'NURTURE',bill_switch_intent:state.billSwitchIntent,contact_preference:preference","rename outcome intent")
must("state.ownerStatus='Sì';state.pvExisting='No';state.roofAvailable='Sì';state.fvIntent='MAYBE';state.result=calculate();","state.ownerStatus='Sì';state.pvExisting='No';state.billSwitchIntent='YES';state.result=calculate();","preview state")

for forbidden in ["roofBlock","roofChoices","roofAvailable","roof_available","fvIntent","fv_intent","MAYBE"]:
    if forbidden in s:
        raise SystemExit(f"forbidden token remains: {forbidden}")
if "bill_switch_intent" not in s or "billSwitchIntent" not in s:
    raise SystemExit("bill switch intent wiring missing")
if "const billFloor=105;" not in s:
    raise SystemExit("bill savings floor missing")
if "valuteresti il cambio bolletta?" not in s:
    raise SystemExit("bill switch question missing")
p.write_text(s,encoding="utf-8")
